<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $id
     * @return null|\AppBundle\Entity\Product
     */
    public function getById($id){
        $qb = $this->createQueryBuilder('p');
        $qb->where($qb->expr()->eq('p.id' , ':idParam'))
            ->setParameter(':idParam', $id);
        $product = $qb->getQuery()->getOneOrNullResult();
        return $product;
    }
}
